export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_FAILURE = "GET_COUNTRIES_FAILURE";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_CITIES = "GET_CITIES";
export const GET_CITIES_FAILURE = "GET_CITIES_FAILURE";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const GET_CITY = "GET_CITY";
