export const GET_HOTELS = 'GET_HOTELS';
export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
export const GET_HOTELS_FAILURE = 'GET_HOTELS_FAILURE';
export const GET_HOTEL_ID = 'GET_HOTEL_ID';
export const GET_HOTEL = 'GET_HOTEL';
